### ISSUE TITLE
Getting "enter correct ZIP code" when entering correct ZIP code?

### ISSUE THREAD

**Issue by TheGamerWithMore** [qconrad/intellistar-emulator#10]
![image](https://user-images.githubusercontent.com/13238845/42691048-b4f524e4-86e5-11e8-9e8d-de37410cb3c2.png)
Im getting this error.... 
:/ help!

**Comment by qconrad** [comment]
Try running the emulator in an incognito window in chrome (Ctrl + Shift + N). If it works, it may be an extension like AdBlock blocking API requests. If this problem still persists, post the developer tools (F12) console tab errors here (if there are any).

**Comment by FNCxPro** [comment]
When did you download the emulator and run it?
Try running it from https://qconrad.github.io/intellistar-emulator

**Comment by FNCxPro** [comment]
@TheGamerWithMore Does the issue still happen? If it does, can you screenshot the DevTools Console?

1. Click *anywhere* on the page, press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>i</kbd> (That's an I, the letter that sounds like eye)
2. Click the "Console" tab at the top of the devtools window that should have appeared, docked in the right side of your chrome window 
![image](https://user-images.githubusercontent.com/9503030/43037382-be193fc4-8cda-11e8-9c27-0a19a4d59f17.png)
3. Create a screenshot of the entire console window's contents, then paste it into a comment at this issue.

**Comment by TheGamerWithMore** [comment]
Hey, it's fixed. Had to disable some plugins.

**Comment by FNCxPro** [comment]
@TheGamerWithMore glad to hear, if you could navigate to #10 and close the issue, that would be great
