### ISSUE TITLE
Issue: Looping not working properly

### ISSUE THREAD

**Issue by DDroid** [qconrad/intellistar-emulator#11]
On  several different devices (_Windows 7, Windows 8.1, Windows 10, Windows 10 XBSS, Android 7.0, and Other Proprietary Software_), and on different browsers (_Google Chrome, IE, Edge, Mozilla FireFox, and Proprietary HTML Browser_) the looping function doesn't seem to be functioning properly. 

I click/tap the TWC logo in the top left of the emulator, and nothing happens at all. I tried to force the "twcLogoClick" command in Google Chrome's console, and still nothing happens. The Autoplay Flags in Google Chrome have been changed appropriately.

Am I doing something wrong?

**Comment by FNCxPro** [comment]
I can reproduce this on my fork and here. It appears the onclick event on the twc-logo element isn't being fired, as I tested by replacing it with console.log and it didn't log anything to the console when it was clicked.

**Comment by DDroid** [comment]
@FNCxPro I see! I'm glad I wasn't the only one experiencing this issue.

I have a question, regarding the looping. Is it intended to auto-start and continuously do that until stopped by the user, or is it just meant to show the settings again without refresh? Is there a way to get it to loop and auto-start (not requiring user input)?

**Comment by FNCxPro** [comment]
It's intended to auto-start and continue on until you click the TWC logo again. Every end of the sequence, it will refresh the page and skip the settings page, since the settings are saved to the local storage (in browsers that support it, it might crash if the browser doesn't support it), the settings are loaded on every refresh before the sequence starts.

**Comment by qconrad** [comment]
I made some changes. Let me know if it fixed in the newest version.

**Comment by DDroid** [comment]
@qconrad (as I cannot test other devices right now) On my Android 7.0 phone, running the latest Google Chrome with autoplay flags correct, it seems it doesn't refresh on it's own, however after the user refreshes it plays automatically. :)

I will test a few other devices when I'm free

**Comment by qconrad** [comment]
My bad. Didn't realize that was broken. Should be fixed now.

**Comment by FNCxPro** [comment]
👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DDroid** [comment]
@qconrad I seems to be almost completely functional as of now, however it only refreshes it once, then after the second time it plays, it gets hung at the end, for an indefinite period of time and will not continue to refresh itself again and again as intended.

**Comment by qconrad** [comment]
Should work now without changing the config.

**Comment by DDroid** [comment]
@qconrad Yes! It's fully working now! Thanks for taking the time to make it right! 😄
