### ISSUE TITLE
Issue: Forecast Timing

### ISSUE THREAD

**Issue by mperezrosas** [qconrad/intellistar-emulator#13]
I've noticed that for most of the daytime, the forecast timing works fine. But sometimes in the evenings the time of day doesn't match the forecast. Screenshots attached. I ran it around 10pm this evening and while the first slide says "tonight" (meaning Sunday night), the actual weather data is for Monday morning. The rest of the slides are off as well - "tomorrow" shows the forecast for tomorrow _night_, and "tomorrow night" shows the forecast for Tuesday.

P.S. Thanks for building this - it's pretty awesome.

![screen shot 2018-07-29 at 10 10 33 pm](https://user-images.githubusercontent.com/41881836/43374712-0b9b3bd0-937f-11e8-900f-3cbc34260cb9.png)
![screen shot 2018-07-29 at 10 10 24 pm](https://user-images.githubusercontent.com/41881836/43374713-0ba97632-937f-11e8-9d3b-fc7587e2f323.png)
![screen shot 2018-07-29 at 10 10 11 pm](https://user-images.githubusercontent.com/41881836/43374714-0bb6ef10-937f-11e8-90c3-205318989829.png)

**Comment by qconrad** [comment]
Thanks for the report. This is fixed now. Better late than never 😉.

**Comment by DDroid** [comment]
Unfortunately, the issue seem to continue to persist for me 
![screenshot 6](https://user-images.githubusercontent.com/13039704/53923183-55ec9580-4045-11e9-9b50-fba7831c8341.png)
