### ISSUE TITLE
Possible solution for Radar?

### ISSUE THREAD

**Issue by zonexero** [qconrad/intellistar-emulator#20]
I have worked on a few weather pages/sites over the years, can something like this help fix the issue with the radar, I had noticed it pulls a gif image, which is what these use....also noticed there is a similar emulator for the weather star system, maybe implementing some of there sources to help fix the broken api?  Would really like to see this fully functional again.

TAMPA BAY RADAR
http://sirocco.accuweather.com/nx_mosaic_640x480_public/sir/inmasirmr_tpa.gif

FLORIDA RADAR
http://images.intellicast.com/WxImages/RadarLoop/pie_anim.gif

**Comment by Brycedoesroblox** [comment]
is there a loop for the Pittsburgh, PA area?

**Comment by RutherfordR** [comment]
I'm thinking of the developers implementing support for Mapbox API Keys.

**Comment by dannyjessee** [comment]
I was able to implement the free [Weather Maps API from RainViewer](https://www.rainviewer.com/api/weather-maps-api.html) to get radar data and display it on [Stadia Maps](https://tiles.stadiamaps.com/). It limits you to just the past two hours of radar data (so "3 Hour Radar" becomes a bit of a misnomer), but it could look like this:

![3HourRadar](https://user-images.githubusercontent.com/1417872/180199500-a463358e-b9ba-448a-9ac5-4ee4b2eda434.PNG)

Obviously this could look even better if we replaced the Stadia Maps base map with one that more closely resembles the base map from the IntelliStar 2, but this was just a quick prototype I threw together.
