### ISSUE TITLE
I have found a solution for Alerts! Please Respond!

### ISSUE THREAD

**Issue by MapGuy11** [qconrad/intellistar-emulator#26]
Hello,

I have found a solution for alerts as I have already implemented the issue of Radar and used Wunderground radar images. I have weather.com's API for alerts but cannot get it to work. Please come back! I see that you are taking on a new project, but this can be great! Please Respond! It Does Work With The Provided API KEY. 

API: https://weather.com/swagger-docs/ui/sun/v3/sunV3AlertsWeatherAlertsHeadlines.json

EDIT: 
Also, I have figured out how to use Weather.GOV's API maybe that can be implemented.
Statewide Alerts: https://api.weather.gov/alerts/active?area=NY
Then You Can Choose Your Closest Station If Wanted: https://api.weather.gov/alerts/NWS-IDP-PROD-4803332-3868420

**Comment by MapGuy11** [comment]
Also, I have figured out how to use Weather.GOV's API maybe that can be implemented.
Statewide Alerts: https://api.weather.gov/alerts/active?area=NY
Then You Can Choose Your Closest Station If Wanted: https://api.weather.gov/alerts/NWS-IDP-PROD-4803332-3868420

**Comment by qconrad** [comment]
Thanks for the info. Last time I checked, I think the weather.com API needed two requests for alerts. It shouldn't be too hard to add. There are sources for radar data out there but finding one that will work easily with this application is harder. I don't plan on abondoning this project, but between new projects and life in general, I can't make any promises on when this will be fixed.

**Comment by MapGuy11** [comment]
Thank you ao much for replying. The API for weather.gov is really easy just pull from the url and it spits the information. I just am not intelligent enough to figure out how to code it. Thank you again for responding and reassuring the project is not dead.

**Comment by A-c0rN** [comment]
> Thanks for the info. Last time I checked, I think the weather.com API needed two requests for alerts. It shouldn't be too hard to add. There are sources for radar data out there but finding one that will work easily with this application is harder. I don't plan on abondoning this project, but between new projects and life in general, I can't make any promises on when this will be fixed.

Hey, I am a software dev who has been working closely with the NWS API lately, if you would like I could make a branch of this repo and take a crack at it.

**Comment by MapGuy11** [comment]
> > Thanks for the info. Last time I checked, I think the weather.com API needed two requests for alerts. It shouldn't be too hard to add. There are sources for radar data out there but finding one that will work easily with this application is harder. I don't plan on abondoning this project, but between new projects and life in general, I can't make any promises on when this will be fixed.
> 
> Hey, I am a software dev who has been working closely with the NWS API lately, if you would like I could make a branch of this repo and take a crack at it.

Wow that would be awesome!

**Comment by MapGuy11** [comment]
> > Thanks for the info. Last time I checked, I think the weather.com API needed two requests for alerts. It shouldn't be too hard to add. There are sources for radar data out there but finding one that will work easily with this application is harder. I don't plan on abondoning this project, but between new projects and life in general, I can't make any promises on when this will be fixed.
> 
> Hey, I am a software dev who has been working closely with the NWS API lately, if you would like I could make a branch of this repo and take a crack at it.

That would awesome!
