### ISSUE TITLE
7-Day Outlook Incorrect

### ISSUE THREAD

**Issue by EmeraldHoax** [qconrad/intellistar-emulator#27]
The 7-day outlook is a day off. It's a minor issue, but I hope you can fix it. For example, when it's Friday and will be sunny, the 7-day outlook will use Saturday's forecast for Friday, and so on. Could ya'll please fix?

**Comment by qconrad** [comment]
Appreciate the report. This is fixed now.

**Comment by EmeraldHoax** [comment]
Thank you so much!
