### ISSUE TITLE
Status Code 401; apiKey possibly expired?

### ISSUE THREAD

**Issue by Selanda** [qconrad/intellistar-emulator#29]
Earlier in the week it was working properly however this morning I'm not able to click the `Start` button on the interface, it doesn't respond to being clicked. Upon further investigation, it appears there's a 401 being retrurned for `https://api.weather.com/v3/location/point?postalKey=18603:US&language=en-US&format=json&apiKey=d522aa97197fd864d36b418f39ebb323` when the button is clicked. I assume due to an invalid/expired apiKey?

**Comment by qconrad** [comment]
Thanks for the report. I'll see if I can get a new API key.

**Comment by relative** [comment]
It looks like `d522aa97197fd864d36b418f39ebb323` is still valid

**Comment by qconrad** [comment]
Hmm. When I tried it earlier, I was able to replicate the error you were referring to but it seems to be working now. Would you able to confirm if it's fixed?

**Comment by Selanda** [comment]
I just tested both API keys and they are both working. I wonder if Weather.com had a hiccup over the weekend which caused `d522aa97197fd864d36b418f39ebb323` to return 401 temporarily?

**Comment by relative** [comment]
> I just tested both API keys and they are both working. I wonder if Weather.com had a hiccup over the weekend which caused `d522aa97197fd864d36b418f39ebb323` to return 401 temporarily?

They may be looking to deactivate the key but might have a legacy application that still uses it, it wouldn't be a bad idea to change to the new key

**Comment by qconrad** [comment]
Seems plausible. I switched it over to the new key. I left the old key as a comment just in case this one breaks for whatever reason. I'm going to close this issue for now but feel free to comment if this error pops up again.
