### ISSUE TITLE
Add Canada support

### ISSUE THREAD

**Issue by novatiberium** [qconrad/intellistar-emulator#30]
Would it be possible to add Canadian support such as taking data/APIs from the Canadian equivalent of TWC (The Weather Network)?

**Comment by RutherfordR** [comment]
They're totally different API systems. It probably won't work.

**Comment by igtampe** [comment]
The current API provides worldwide info. Canada support has been added:

<img width="279" alt="image" src="https://github.com/qconrad/intellistar-emulator/assets/49919240/a6ddb38d-e31e-4ba1-8297-d97a71f5329f">

<img width="1368" alt="image" src="https://github.com/qconrad/intellistar-emulator/assets/49919240/e3910a46-9b2f-4388-b1fe-4b224e20cc5f">

**Comment by adamssecretcode** [comment]
Just found this project, and luckily I see Canada is an option! Thanks for adding that! In Canada, we use Metric, is there a possibility of having a metric option? I ask this knowing nothing about the complexity of the work. Very cool project!

**Comment by qconrad** [comment]
Metric is technically supported, there's just no UI for it at the moment. Here's how you can switch to metric.

1. Before clicking start, open browser developer tools (Ctrl+Shift+I), select the "Console" tab, paste "window.CONFIG.units = 'm'" (without the quotes), and hit enter. You will have to do this every time though.
2. If running locally, you can edit _js/Config.js_ line 5 for a more persistent option.

**Comment by adamssecretcode** [comment]
thank you!
