### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by coolguyunblocked** [qconrad/intellistar-emulator#32]

**Comment by tvongsaly4592** [comment]
https://developer.accuweather.com/?gclid=Cj0KCQjwl92XBhC7ARIsAHLl9alu7BvB98-01ZTFHHydYnrgxJg1B2x30_HvmThQEGWaUug1WchOdCMaAhF9EALw_wcB

**Comment by googleuser3212** [comment]
If i would like to manually add this into my copy of this, how would i go about doing that?
