### ISSUE TITLE
Suggestion: animated forecast icons

### ISSUE THREAD

**Issue by JGriffin34432** [qconrad/intellistar-emulator#6]
Is it possible for you to replace the icons with ones that animate with each other?

**Comment by FNCxPro** [comment]
I was working on animated icons from the SVGs that we have in the repository, never got anywhere. I plan on doing that and opening a pull request

**Comment by qconrad** [comment]
Animated icons really liven up the entire presentation. One of the biggest distinctions between the original. I don't have any experience with animating SVGs but huge props if you can get them to work.
